### ISSUE TITLE
grid lines:  Lab Values vs. Upper Limit of Normal by Visit

### ISSUE THREAD

**Issue by zskrivan** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#114]
Please add minor and major grid lines to the "Lab Values vs. Upper Limit of Normal by Visit" plot so we can easily compare the values over time.

**Comment by jwildfire** [comment]
Added major gridlines in the commit above. Adding minor lines isn't a standard feature in webcharts (aka it's a bit more work), so lets see if this is sufficient
