### ISSUE TITLE
R score calculation

### ISSUE THREAD

**Issue by JimBuchanan** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#133]
I noticed that the R Ratio is described on the tool as "R Ratio (ALTxULN / ALPxULN)". The actual calculation is [(ALT/ULN) / (ALP/ULN)]. Can we confirm how the tool is calculating the R ratio?

**Comment by jwildfire** [comment]
I can confirm that the label is incorrect, Jim. I'll do a quick release to update the label once all the pending releases are out the door.

**Comment by JimBuchanan** [comment]
Perfect. Thanks for confirming.

Jim
