### ISSUE TITLE
Clicking on point causes stack size error

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#156]
Behavior observed in R implementation on Windows machine in enlarged viewer window and/or web browser (oddly, behavior is normal in the small RStudio viewer window).  

For the problematic situations, clicking on point successfully generates participant details but neither of the subsequent displays.  Specifically, the following behavior/error is observed in console upon clicking on point: 

![image](https://user-images.githubusercontent.com/14199771/46101141-30f01e80-c199-11e8-9c87-eccaa0fdfc91.png)

**Comment by jwildfire** [comment]
Will investigate next week. Curious to see:
- whether this was introduced in v0.16.0 or happened in earlier builds
- whether it happens with data sets of all sizes

**Comment by jwildfire** [comment]
In fact, @bzkrouse: if you have time, could you subset the test data and see if the error still occurs when the data set is cut down to only a few subjects?

**Comment by bzkrouse** [comment]
@jwildfire sure - and yes, the error remains with 5 subjects :(

**Comment by jwildfire** [comment]
Updated the R package to use to the latest commits for both eDish and webcharts, and tested on mac and PC - stack error *appears* to be resolved in both environments.  @bzkrouse can you confirm? 

```
devtools::install_github("ASA-DIA-InteractiveSafetyGraphics/ReDish", ref="v0.1.1-dev")
library(ReDish)
eDISH(data=adlbc)
```

**Comment by bzkrouse** [comment]
@jwildfire working for me on Windows/PC!
