### ISSUE TITLE
data specification

### ISSUE THREAD

**Issue by hongmuw** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#157]
do we need to update data specification? I can see we are using ADaM dataset, but variables listed in data specification are not updated yet, but this is not urgent.

**Comment by jwildfire** [comment]
@hongmuw - Thanks for this comment. The wiki page was actually incorrect. The chart uses SDTM, not ADaM, by default. I've updated the [data guidelines wiki page](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/wiki/Data-Guidelines) to clarify and add a link to a customized version of the chart that does use ADaM. Let me know if that helps!

**Comment by jwildfire** [comment]
On a related note, we certainly *could* use ADaM instead of SDTM by default. We tend to use the charts for ongoing monitoring more than as a final analysis/submission-related tool, so SDTM makes a bit more sense for that use case. Not at all sure that is the case for everyone though.

**Comment by jwildfire** [comment]
Closing this for now. Can re-open if someone wants to make the case for changing defaults from SDTM to ADaM
