### ISSUE TITLE
settings.group_cols accepts array of variable names, not array of objects

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#161]
Per wiki, group_cols is meant to accept an array of objects, each object specifying value_col and label for a given filter.  Actual implementation uses array of variable names.

**Comment by jwildfire** [comment]
Probably just going to update the documentation to be accurate instead of supporting labels at this time.

**Comment by jwildfire** [comment]
It actually accepts either an array of strings or an array of objects - [code here](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/blob/master/src/configuration/syncSettings.js#L5-L14). If an array of strings are provided (`["TRT","AGEGROUP"]`), it is changed in to the appropriate object layout by the function above: 

```
[
  {label:"TRT",value_col:"TRT"},
  {label:"AGEGROUP",value_col:"AGEGROUP"}
]
```

Just noticed custom labels aren't being applied, so created #164 to deal with that.

**Comment by bzkrouse** [comment]
@jwildfire - ah yes I see this now.  I'll go ahead and work that back into the R side.
