### ISSUE TITLE
Add option for paneling by groups

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#37]
## Clinical Summary

Add an option to create multiple eDish panels for a categorical variable (e.g. treatment). This could be instead of, or in addition to, the current color-by-group functionality. 

## Details

Probably possible to set this up via `webcharts.multiply`, but definitely not trivial with all of the custom interactivity, so leaning towards skipping this for now.

**Comment by JimBuchanan** [comment]
Consider for v2.0.

**Comment by jwildfire** [comment]
The more I think about this, the less I like the idea. Going to close this for now. We can re-open and discuss further if/when users start requesting this functionality.
