### ISSUE TITLE
Expand Quadrant table to show participant summaries

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#39]
## Clinical Summary

Allow user can expand a given quadrant in the summary table to show a list of participants in that quadrant.

**Comment by JimBuchanan** [comment]
Either a list of participants in a quadrant, or display subject identifier if you hover the cursor over a dot. Clicking on dot to bring up a spaghetti plot of lab analytes is a powerful feature and desirable for v1.0. Other data to display with the spaghetti plots, such as study drug exposure, concomitant medications, an AEs can be saved for v2.0.

**Comment by jwildfire** [comment]
Not sure this is much value added here. Closing this for now. Can re-open and discuss further if/when users request a more detailed summary table.
