### ISSUE TITLE
Add R Ratio Filter

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#61]
## Clinical Summary 

Add a filter for R Ratio/R Score. 

## Details

Notes below from @JimBuchanan:

The other ALP filter uses what is called the “R ratio” or “R score”. The R ratio is calculated as:
 (ALT value/ULN for ALT) / (ALP value/ULN for ALP)
 
An R value of ≥5 indicates hepatocellular injury, >2 to <5 mixed-type injury and ≤2 cholestatic injury.

**Comment by JimBuchanan** [comment]
This would be an important feature to include in v1.0.

**Comment by jwildfire** [comment]
Initial implementation is almost done - Added a new control allowing a user to set a minimum R Ratio value. All values below this cut point are hidden - default value = 0. This is controlled by 2 settings: 

`config.r_ratio_filter` - boolean indicating whether the R ratio filter should be shown. 
`config.r_ratio_cut` - numeric indicating the default value of the R ratio cut point. User can change this value
