### ISSUE TITLE
Highlight proximal Hy's Law points

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#64]
## Clinical Summary

Add toggle to highlight participants with Hy's law qualifying points within 30 days. 

**Update**: Prototype available [here](https://rawgit.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/11c0768d6e84bd44c69f4d91f5a85166793d0f74/test/)

**Comment by jwildfire** [comment]
Let the user select the number of days here (default = 30). This control will replace the current color gradient showing # of days between visits.

**Comment by zskrivan** [comment]
The default window should be the entire length of the trial; ie 'no window'.

**Comment by jwildfire** [comment]
Interesting, perhaps there should be 2 controls: 
(1) Highlight points based on time window (checkbox, default = not checked)
(2) Select Time window (numeric control, default = 30 days)
 
(2) could be hidden until (1) is checked. 

We could also just have a numeric control that defaults to the trial length, but I feel like having huge numbers (10,203) come up by default with little explanation is a bit awkward.

**Comment by JimBuchanan** [comment]
The default could be 30 days with the user ability to vary the time window (as you demonstrated live today).
