### ISSUE TITLE
Add toggle to show all visit-level points on main chart

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#76]
## Clinical Feature

A new control would allow users to see visit level data along with the participant level eDish measure. The visit level data is currently visible by clicking on a participant's point, but this view would show all participants' points simultaneously. 

## Details

We would probably add a checkbox for "Show visits" which would be unchecked by default. The visit points would need to look different than the participant-level points (smaller radius, different color) and we'd need to add a legend.

**Comment by JimBuchanan** [comment]
I think I need to see an example to make sure I'm understanding the visualization correctly.

**Comment by jwildfire** [comment]
Yeah, this is a bit hard to describe. I'll work on a quick prototype in the next round of updates.

**Comment by jwildfire** [comment]
Team decided that this isn't needed.

See #104 if we decide to revisit after v1.0
