### ISSUE TITLE
Establish clinically relevant thresholds for mDish

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#78]
## Clinical Feature

When the page is loaded, thresholds for mDish based should default to values based on the literature

## Details

I just chose some arbitrary thresholds to get us started, but it would be much better to have clinically relevant defaults. Do you know of any relevant literature, @JimBuchanan?

**Comment by JimBuchanan** [comment]
The paper by Lin et al. (2012) recommends an ALT threshold of 3.8 x baseline and a bilirubin threshold of 4.8 x baseline for the mDISH. The use of baseline-corrected data diminishes inter-laboratory variation and may be more sensitive to possible drug effects. The baseline-corrected data method of mDISH is a useful complementary method with eDISH. Lin X, Parks D, Painter J, et al. Validation of multivariate outlier detection analyses used to identify potential drug-induced liver injury in clinical trial populations. Drug Safety 2012;35:865-875.

**Comment by JimBuchanan** [comment]
Jeremy,

I just posted a reply in github citing the recommended mDISH thresholds and the source.

Thanks,

Jim

**Comment by jwildfire** [comment]
Great! I'll make the update in the next release.
