### ISSUE TITLE
Remove cutpoint info from measure_details setting

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safety-eDISH#83]
The `measure_details` setting (default [here](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/blob/master/src/defaultSettings.js#L15-L49)) is currently quite complex and contains a lot of the key settings for customizing the eDish display. Consider either refactoring to separate the various interests in to multiple configurable settings (`cut_details`, `axis_details`, etc.). At the very least it might be worth creating a separate wiki page with a vignette to explain how to update the setting for different data sources.

**Comment by jwildfire** [comment]
I'm thinking the revised settings would look something like this: 

```
measures:[
  {
      label: 'ALT',
      value: 'Aminotransferase, alanine (ALT)'
  },
  ...
],
cuts:[
  {
    label:"ALT",
    relative_baseline: 3.8,
    relative_uln: 3,
    absolute: 1.0
  },
  ...
],
imputation:[
  {
    label:"ALT",
    imputation:"data-driven"
  },
  ...
],
x_options:["ALT","AST","ALP"],
y_options:["TB"],
size_options:["ALT","AST","TB","ALP"]
```

Instead of the current settings like this:

```
measure_details: [
    {
        label: 'ALT',
        measure: 'Aminotransferase, alanine (ALT)',
        axis: 'x',
        imputation: 'data-driven',
        cut: {
            relative_baseline: 3.8,
            relative_uln: 3,
            absolute: 1.0
        }
    },
    ...
]
```

**Comment by jwildfire** [comment]
Or perhaps: 
```
cuts: {
    "ALT":{
       relative_baseline: 3.8,
       relative_uln: 3,
       absolute: 1.0
     },
  ...
},
imputation:{
"ALT":"data-driven",
  ...
},
```

**Comment by jwildfire** [comment]
Editing this issue to break in to smaller chunks. This issue will just cover the cutpoint refactor. Making separate issues for imputation and the various axis/size options

**Comment by samussiah** [comment]
Like the lookup object more than the array for sure.
